In [3]:
import pandas as pd
import numpy as np

import sys

In [6]:
# Подготовка данных

# Чтение данных с наименованиями полей
data_column_names = pd.read_excel('../input_data/data_from_site3.xlsx', sheet_name='names')

# Удаление событий сс пустыми значениями в поле checked_parameter
data_column_names['checked_parameter'].replace('', np.nan, inplace=True)
data_column_names.dropna(subset=['checked_parameter'], inplace=True)

# Получение списка исследуемых параметров
list_data_necessary=[]
for n_data in data_column_names['N']:
    list_data_necessary.append(n_data)
    
# Получение всех данных теста
data_all = pd.read_excel('../input_data/data_from_site2.xlsx', sheet_name='data')

# Получение данных по иследуемым параметрам
data_necessary=data_all[list_data_necessary]
data_necessary.head()

# Переименование заголовков столбцов
old_names = list_data_necessary
new_names = data_necessary.loc[0]
data_necessary.rename(columns=dict(zip(old_names, new_names)), inplace=True) 
data_necessary.drop([0], inplace=True)

# !!! Предварительно нужно провести нормализацию столбцов

# Объединение столбцов с пенсией и зарплатой
data_necessary.loc[data_necessary['Средняя_зарплата_месяц']=='     .  ', 'Средняя_зарплата_месяц']=data_necessary['Сумма_пенсии']
data_necessary.rename(columns=dict(zip(['Средняя_зарплата_месяц'], ['Размер_зарплаты_пенсии'])), inplace=True) 
del data_necessary['Сумма_пенсии']   

data_necessary.head()

C:\Users\Tasha\anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Степень_состоятельности,Степень_власти,Степень_уважения_другими,Состав_семьи,Наличие_детей,Уровень_образования,Наемный_работник,Владелец_предприятия,ИП,Фермер,Свободный_работник,Профессия_должность,Деятельность_компании,Размер_зарплаты_пенсии,Верующий,Пользование_интернетом,Мессенджеры_нет,Проживание_область,Проживание_населенный_пункт
1,6,3,5,5,1,3,1,0,0,0,0,бухгалтер ...,пекарня ...,25000,1,3,1,24,1
2,4,3,6,1,1,1,.,.,.,.,.,...,...,7000,1,1,.,70,2
3,4,6,6,3,2,3,1,0,0,0,0,санитарка ...,Медицина ...,15000,1,3,0,19,1
4,2,2,3,4,1,3,.,.,.,.,.,...,...,.,1,2,1,4,2
5,1,99,9,1,1,1,.,.,.,.,.,...,...,10178,1,1,.,92,1

In [ ]:
data_necessary.to_excel('../output_data/data_to_experiments.xlsx', sheet_name='data')